### ISSUE TITLE
Upgrade to Funkwhale 0.21

### ISSUE THREAD

**Issue by EliotBerriot** [YunoHost-Apps/funkwhale_ynh#101]
Hi there, I'm just opening this issue as a reminder. Our [first release candidate for Funkwhale 0.21 is out](https://governance.funkwhale.audio/d/SeUDP7vM/funkwhale-0-21-release-incoming-looking-for-testers-) and you way want to think about upgrading `funkwhale_ynh` package as a result. The actual release is due around April 21.

As far as I can tell, it should be really easy, since we shouldn't have any backward incompatible changes regarding deployment. According to the changelog, there is [a small tweak to the nginx configuration, to ensure the Funkwhale PWA works properly](https://dev.funkwhale.audio/funkwhale/funkwhale/-/tags/0.21-rc1#progressive-web-app-manual-action-suggested-non-docker-only), but that's pretty much it.

Let me know if I can be of any help, and thank you very much for the work you're doing on `funkwhale_ynh`.

**Comment by Jibec** [comment]
Le 2020-04-10 13:59, Eliot Berriot a écrit :
> Let me know if I can be of any help, and thank you very much for the
> work you're doing on funkwhale_ynh.

Thank you Eliot. You are doing most of it, and I am glad to be help with 
this tiny contribution.

Side request: you know I promote internationalization, I would love to 
see a call for translators when you do a beta ;)

**Comment by EliotBerriot** [comment]
> Side request: you know I promote internationalization, I would love to
see a call for translators when you do a beta ;)

Oh, we did actually, on [Mastodon](https://mastodon.eliotberriot.com/@funkwhale/103967696105254045) and our [forums](https://governance.funkwhale.audio/d/X2z5kEFt/coordinate-translations/36). Maybe there is a better channel, like weblate, because I definitely understand how some people could miss this.

**Comment by EliotBerriot** [comment]
`0.21-rc2` published this morning, final release scheduled by the end of the week

**Comment by Jibec** [comment]
Ok, I'll try to have a look by then.

About translations, I only read the link Eliot shared, and now that I 
read a little more, it's great to see you included translation 
activities in your announcements.
 From the few things I saw, you definitely are building a great community 
and are an example to follow.

**Comment by Jibec** [comment]
I finally decided to retire from package maintenance, is app is now unmaintained, sorry Eliot

**Comment by EliotBerriot** [comment]
It's okay @Jibec, you don't have to apologize.

You've maintained this for years, and it is truly useful to a lot of people, I think we should be thankful toward you and others contributors of this package  💜

Thank you for letting us know, it that's okay with you, I have a question regarding the package. I definitely don't want to take more of your time and energy, but if I find someone willing to take over the maintainance, would you be consider transferring the repo to them?

**Comment by novadeviator** [comment]
I really hope someone steps up... Thank you @Jibec for all the work on this so far!!!

**Comment by Sporiff** [comment]
The application has been updated in !105
