### ISSUE TITLE
Firewall port 4040 needs to be openned for subsonic API

### ISSUE THREAD

**Issue by fragilbert** [YunoHost-Apps/funkwhale_ynh#102]
It's in the title. I had to manually set the rule after installation.

**Comment by Sporiff** [comment]
Thanks for the report. I'll have a look at opening this up during install (or rather making this configurable if possible)

**Comment by tim-huggins** [comment]
Did you have to change anything else? I can not connect to the funkwhale subsonic server either. I opened port 4040 on my router and in yunohost but still nothing.

**Comment by shukon** [comment]
Same here. Not able to connect via subsonic. Any workarounds?
(thank you for this amazing piece of software!)

**Comment by tim-huggins** [comment]
@shukon I never found a resolution. Ultimately I uninstalled YunoHost and installed Funkwhale directly

**Comment by yalh76** [comment]
subsonic API should be working by now, as described in https://docs.funkwhale.audio/developers/subsonic.html?highlight=subsonic, it's directly handled by nginx
