### ISSUE TITLE
Funkwhale 1.0 will drop Python 3.5 compatibility

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/funkwhale_ynh#103]
Some bad news, I guess...

> The next release, Funkwhale 1.0, will drop compatibility with Python 3.5, which is the version installed on Debian 9.
> 
> We'll be officially removing some compatibility tweaks for Python 3.5 on the develop branch (0.21 and 0.21.x hotfixes won't be affected). 
> 
> If your pod run on develop and debian 9, we recommend upgrading to debian 10, which includes Python 3.7. You will also need to recreate your virtualenv (https://docs.funkwhale.audio/installation/debian.html#python-dependencies).
> 
> If you run on another OS, ensure `python3 --version` returns 3.6 or higher.
> 
> If you run Funkwhale using Docker, you can safely ignore this ;)

https://mastodon.eliotberriot.com/@funkwhale/104110393961790849

**Comment by Tagadda** [comment]
We could use pythonz, as Bram pointed out.

YunoRunner does like this https://github.com/YunoHost-Apps/yunorunner_ynh_core/blob/b44c991d2fd7af2d111828409ad6f7b11a26bbaf/scripts/install#L106

**Comment by Sporiff** [comment]
That might be an idea, although we are a little ways off Funkwhale 1.0 and Yunohost may migrate to Debian 10 beforehand. If not, we can look at implementing this closer to the time. #105 contains compatibility fixes for Python 3.5 in the meantime.

**Comment by petitminion** [comment]
any news on funkwhale 1.0 for yunohost ? thx ! :)

**Comment by cristianvogel** [comment]
yes, I am also interested in Funkwhale 1.0 , because it has some monetisation features that our artists would definitely like to use

**Comment by Sporiff** [comment]
@petitminion @cristianvogel I've pushed some changes to the testing branch which should handle the update to 1.0. This works on my system, but I'd like to get some more people testing it before I merge it to the main branch just to be sure. I've not got much time to dedicate to this, but hopefully changes will be small following 1.0.

**Comment by Thovi98** [comment]
> 
> 
> @petitminion @cristianvogel I've pushed some changes to the testing branch which should handle the update to 1.0. This works on my system, but I'd like to get some more people testing it before I merge it to the main branch just to be sure. I've not got much time to dedicate to this, but hopefully changes will be small following 1.0.

Hello @Sporiff !
Thank you sooo so much for this update ! Worked without any issue for me. I’m so happy 😃

**Comment by alfredo87** [comment]
thank you. i have upgraded to 1.0 and it works on yunohost merci.
