### ISSUE TITLE
Easyfix: please finish maintainership transfer

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/funkwhale_ynh#107]
Hello,

could you please please replace my mail address there by yours?
https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/check_process#L28

You may read this to tune behavior: https://github.com/YunoHost/package_check#-options

You can also include me as previous maintainer, see this example: https://github.com/YunoHost-Apps/kresus_ynh/blob/master/manifest.json#L15

thank you for your help, and all the best in your journey

**Comment by Sporiff** [comment]
Hi @Jibec 

No problem. Thanks for the links!

**Comment by Sporiff** [comment]
This has been resolved in the latest commit
