### ISSUE TITLE
Is ynh >= 3 a strong requirement ?

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/funkwhale_ynh#11]
Any particular reason to require ynh >= 3 ?

Can't wait to test funkwhale, thanks for packaging <3.

**Comment by Jibec** [comment]
hello, yes, Funkwhale requires Python >= 3.5 which is only Debian 9 (Ynh >= 3). And I had it patched so it doesn't require Python 3.6...
https://packages.debian.org/search?keywords=python3&searchon=names&suite=all&section=all

**Comment by JocelynDelalande** [comment]
OK, thanks :-)
