### ISSUE TITLE
No  Open registrations to new users

### ISSUE THREAD

**Issue by vicdorke** [YunoHost-Apps/funkwhale_ynh#113]
Error while saving settings
A server error occured

Jul 09 02:47:55 funkwhale-server[8300]:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/dynamic_preferences/api/serializers.py", line 69, in update
Jul 09 02:47:55 funkwhale-server[8300]:     instance.value = validated_data['value']
Jul 09 02:47:55 funkwhale-server[8300]:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/dynamic_preferences/models.py", line 53, in set_value
Jul 09 02:47:55 funkwhale-server[8300]:     self.raw_value = self.preference.serializer.serialize(value)
Jul 09 02:47:55 funkwhale-server[8300]:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/dynamic_preferences/serializers.py", line 39, in serialize
Jul 09 02:47:55 funkwhale-server[8300]:     return cls.to_db(value, **kwargs)
Jul 09 02:47:55 funkwhale-server[8300]:   File "/var/www/funkwhale/code/api/funkwhale_api/common/preferences.py", line 75, in to_db
Jul 09 02:47:55 funkwhale-server[8300]:     "{} is not a valid value: {}".format(value, data_serializer.errors)
Jul 09 02:47:55 funkwhale-server[8300]: dynamic_preferences.serializers.SerializationError: {'fields': [], 'help_text': {'content_type': 'text/markdown', 'text': None}} is not a valid value: {'help_text': {'text': [ErrorDetail(string='This field may not be null.', code='null')]}}
Jul 09 02:47:55 funkwhale-server[8300]: [2020-07-09 06:47:55 +0000] [8307] [INFO] ('127.0.0.1', 55578) - "POST /api/v1/instance/admin/settings/bulk/ HTTP/1.1" 500

**Comment by yalh76** [comment]
Have you tryed with last version ?
