### ISSUE TITLE
1.0.1 released

### ISSUE THREAD

**Issue by hieronymousch** [YunoHost-Apps/funkwhale_ynh#118]
https://dev.funkwhale.audio/funkwhale/funkwhale/-/releases#1.0.1

**Comment by Thovi98** [comment]
It’s on the testing branch, if you want to test it : `sudo yunohost app upgrade funkwhale -u https://github.com/YunoHost-Apps/funkwhale_ynh/tree/testing --debug`

**Comment by hieronymousch** [comment]
Just tested the upgrade and works fine. Thanks!

**Comment by MyNameIsTroll** [comment]
I have just made the update just now, everything went well 👍 
Thank you very much for your work.

Machine: Raspberry pi 4
Version of YNH: 4.0.8.3 (stable)

Small remark, the version number of the package seems incorrect. We have the impression that it regresses ^^


![image](https://user-images.githubusercontent.com/31790025/101984809-13c59e80-3c84-11eb-8bb0-e8b1f2b5344a.png)

**Comment by Thovi98** [comment]
> I have just made the update just now, everything went well 👍

You made the master branch (Funkwhale 1.0) update I think (through the admin interface)
`sudo yunohost app upgrade funkwhale -u https://github.com/YunoHost-Apps/funkwhale_ynh/tree/testing --debug` will put you on 1.0.1 and the version number will be correct.

**Comment by yalh76** [comment]
Already at 1.1
