### ISSUE TITLE
Newly imported album covers are not displayed

### ISSUE THREAD

**Issue by IsidoreIsou** [YunoHost-Apps/funkwhale_ynh#128]
After last update (1.0.1), when I import a new album (tagged with Picard), the cover art won't appears on the funkwhale interface. It will appears when using a mobile app (dsub). The cover is present in the admin area.

**Comment by yalh76** [comment]
Have you tryed with last version ?

**Comment by IsidoreIsou** [comment]
Problem seems solved now (1.1.1).
