### ISSUE TITLE
Clarify steps necessary to add music to a library in yunohost installation of funkwhale

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/funkwhale_ynh#132]
Funkwhale documentation provides instructions for importing / connecting to external music shares or collections here:
https://docs.funkwhale.audio/admin/importing-music.html#in-place-import

>We recommend you symlink all your music directories into /srv/funkwhale/data/music and run the import_files command from that directory. This will make it possible to use multiple music directories, without any additional configuration on the webserver side.

However, this recommended directory does not exist on a Yunohost installation of Funkwhale. Other examples of what to do with docker images / etc. exist on the Funkwhale documentation site but it's not clear if any of those apply to Yunohost installations.

Currently the readme for the funkwhale app states:
<img width="840" alt="Screenshot 2021-04-02 at 17 52 04" src="https://user-images.githubusercontent.com/1538027/113431517-27844480-93dc-11eb-94e8-ed64af8ee26b.png">

However, it's not clear (to this user) what must be done, because executing that command results in an error:
<img width="579" alt="Screenshot 2021-04-02 at 18 11 51" src="https://user-images.githubusercontent.com/1538027/113433171-ffe2ab80-93de-11eb-9305-0d7fe276971b.png">

Without that working it seems unlikely the manage.py commands will work for command line import.

Since 1) This will be a common need for many users and 2) The existing funkwhale documentation will not apply because the various paths are different, we should clarify the necessary steps to import music from different locations (like an attached drive or a network share) in the readme.

**Comment by Thovi98** [comment]
If I understand well, you want to use your tracks in `/home/yunohost.multimedia/share/Music/` in Funkwhale ?
Try to symlink `ln -s /home/yunohost.multimedia/share/Music/ /var/www/funkwhale/import`

If that works, I will make a PR to include it in the Readme.md.

**Comment by lightnin** [comment]
This is after a restore of a full system yunohost backup onto a new install / SD card. Where previously I had my music symlinked to a share in /var/www/funkwhale/import, this symlink wasn't restored by the backup (neither was the NFS network mount - but perhaps this is out of the scope of a yunohost backup.) I have since restored the symlink as you suggest, but where previously (at least in 1.0) the library would indicate an import function in library upload below "Import Music from your Server", now it does not. So - not sure what to try next. 

I'm assuming the potential steps to put in the readme for users of this app are as follows:
1. Install via yunohost.
2. Create symlink to your music library in /var/www/funkwhale/import (This directory didn't exist for me at start, at least after restore.) 
3. Create a new library, select import tab, (then what?)
Normally I would say this level of instruction would be beyond the scope of a yunohost app, and would instead refer users to the funkwhale documentation. But my argument is that we need to provide a clear set of documented steps for yunohost users because the funkwhale documentation doesn't accurately apply because the directories / locations don't apply to Yunohost installations.
