### ISSUE TITLE
Update to 1.1.1

### ISSUE THREAD

**Issue by Thovi98** [YunoHost-Apps/funkwhale_ynh#135]
There is a new Funkwhale update since yesterday.
https://dev.funkwhale.audio/funkwhale/funkwhale/-/releases/1.1.1

I was beginning to update this package, but I was wondering : is it best to update from `testing `or directly from `example` ? @yalh76 any suggestion here ?

**Comment by yalh76** [comment]
better from example ;) as it's a full rework ^^
