### ISSUE TITLE
increase upload filesize

### ISSUE THREAD

**Issue by baensch** [YunoHost-Apps/funkwhale_ynh#139]
Hi Together,
i have some huge FLAC files which i wanted to upload but when i try the upload is rejected.
![grafik](https://user-images.githubusercontent.com/66867627/115253937-2b7acb00-a12d-11eb-9aa2-f1a961c207e4.png)
I already tried to increase the file upload in my nginx conf but maybe on the Wrong place or it is ignored.
These are the configurations where i tested it:
```
/etc/nginx/nginx.conf
/etc/nginx/conf.d/mydomain.conf
```
every time i added `client_max_body_size 200M` an restarted the Server. But it says still rejected.

**Comment by Thovi98** [comment]
The nginx conf is located at `/etc/nginx/conf.d/funkwhale.domain.tld.d/funkwhale.conf`.

I'm not home so I cannot help you more right now, but feel free to ask if it doesn't work, I'll try to help you.

**Comment by baensch** [comment]
Thank you very much. It work now.
