### ISSUE TITLE
Upgrade from 1.1~ynh1 to 1.1.1~ynh1 tries to backup remote linked music library to /home/yunohost.app/funkwhale/data/music

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/funkwhale_ynh#141]
### Describe the bug

In the process of upgrading  from 1.1~ynh1 to 1.1.1~ynh1 via admin interface, the system appears to attempt to "backup" music data that is mounted via NFS on a remote server by copying it to: /home/yunohost.app/funkwhale/data/music. When this data is too large to fit on the SD card, the copy fills up the entire SD card, the upgrade fails and the system becomes unstable for lack of storage space. 

Workaround: Delete contents of: /home/yunohost.app/funkwhale/data/music to restore space to the system.

### Context

- Hardware: Rpi 4
- YunoHost version: 4.1.8 (stable).
- I have access to my server:  Through SSH | and through the webadmin | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch:

### Steps to reproduce

Symlink remote library NFS share to /var/www/funkwhale/import (greater than size of SD card)
Import remote music files by clicking Import on library tab. (Default behavior should be in place import)
Attempt to upgrade  from 1.1~ynh1 to 1.1.1~ynh1 via admin interface

### Expected behavior
The upgrade should be successful. The upgrade script should not try to backup music files on a remote drive.

**Comment by yalh76** [comment]
It don't try to backup the music files on a remote drive, it try to move music to a a definitive path, outside of the application.

**Comment by lightnin** [comment]
Thanks.  But there will still be problem if it tries to move a large collection of files from a remote drive (where there is space) to the SD Card (where there is not enough space), right?

**Comment by yalh76** [comment]
another option would be to unmount the music data, do the upgrade and the remount it at `/home/yunohost.app/funkwhale/data/music`
