### ISSUE TITLE
funkwhale-beat dies continuosly

### ISSUE THREAD

**Issue by noccio** [YunoHost-Apps/funkwhale_ynh#147]
As reported in https://forum.yunohost.org/t/funkwhale-beat-dies-always/16360

Raspberry pi4 at home
funkwahle version 1.1.2~ynh1

https://paste.yunohost.org/ofizuqopuy is the log I can read from webadmin

Someone in the matrix channel for funkwhale talked about some permission error.

**Comment by Thovi98** [comment]
I had the same problem. Connect to ssh and type `mv /var/www/funkwhale/api/celerybeat-schedule.db /var/www/funkwhale/api/celerybeat-schedule_old.db`. This will recreate the file. Then start the service again.

**Comment by noccio** [comment]
It worked, thanks!
