### ISSUE TITLE
Upgrade to 1.1.4~ynh1 takes > 2 hours, FNF error media attachments

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/funkwhale_ynh#151]
### Describe the bug

Upgrade to  1.1.4~ynh1 via admin interface from previous version takes > 2 hours, and appears to throw a great deal of errors. 

### Context

- Rpi4
- YunoHost version: 4.2.7
- I have access to my server: *Through SSH and through the webadmin  
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: 1.1.4~ynh1
- If upgrading, current package version: previous funkwhale release

Music / media library shared via NFS, symlinked in /home/yunohost.app/funkwhale/data/music
Media library is ~300 GB.

### Steps to reproduce
System update page, update system, update all apps (Funkwhale was only app that had an update.)

### Expected behavior

Upgrade completes in timely fashion, doesn't throw errors.

Screenshot taken approx. 2 hours after start of upgrade indicated.

![Screenshot 2021-08-13 at 10 51 35](https://user-images.githubusercontent.com/1538027/129332481-7a9766ed-1d02-4f6b-a44e-15f811195b4c.png)

### Logs

Not sure how to interrupt the process, will add logs once it completes or otherwise stops. 

*When an operation fails, YunoHost provides a simple way to share the logs.*
- *In the webadmin, the error message contains a link to the relevant log page. On that page, you will be able to 'Share with Yunopaste'. If you missed it, the logs of previous operations are also available under Tools > Logs.*
- *In command line, the command to share the logs is displayed at the end of the operation and looks like `yunohost log display [log name] --share`. If you missed it, you can find the log ID of a previous operation using `yunohost log list`.*

*After sharing the log, please copypaste directly the link provided by YunoHost (to help readability, no need to copypaste the entire content of the log here, just the link is enough...)*

*If applicable and useful, add screenshots to help explain your problem.*

**Comment by lightnin** [comment]
Rebooted server at 4 hours from start. It looks like despite the constant erroring, the upgrade was successful as pod says 

Funkwhale version | 1.1.4+git.3c8c1524

so perhaps the problem I was seeing was in some sort of post-processing step. 

The interesting thing is that I left the tab with the admin upgrade dialog that was running open, and after the server reboot it is still continuing to chug along as though the error messages it is showing are happening now. So is there some kind of nasty queuing going on behind this? 

![image](https://user-images.githubusercontent.com/1538027/129344935-d30af15d-4322-45dd-b156-32d7a43ace94.png)

**Comment by lightnin** [comment]
Upgrade log: https://paste.yunohost.org/raw/ovogoziluy
Note that in case this is an issue with my browser / some kind of sick JS queing thing, I'm running FF 90.0.2

**Comment by yalh76** [comment]
Well, you error was on regenerating the thumbnails

https://github.com/YunoHost-Apps/funkwhale_ynh/blob/427bc26b258d2dfa880e3df77a7c19ff37beaefe/scripts/upgrade#L246

This was introduced for funkwhale 1.0, I will removed it
