### ISSUE TITLE
Incorrect Data Directory Location

### ISSUE THREAD

**Issue by tryptophonic** [YunoHost-Apps/funkwhale_ynh#152]
### Describe the bug

Incorrect data directory location after fresh install of 1.1.4~ynh1.

### Context

- VPS
- YunoHost version: 4.2.7

### Steps to reproduce

- On a fresh install, after logging in, I'm unable to upload both images or audio.
- On the frontend, there is no noticeable error - images apparently upload but just appear blank, as does audio.
- Checking the nginx funkwhale error log, I see a series of errors - [filename] "failed (2: No such file or directory)"
- the error messages mention directories starting "/home/yunohost.app/funkwhale/data/media/....", looking in /home/yunohost.app/funkwhale/ I have three directories media, music and static - but no data directory. 
- In other words, it appears that the "/home/yunohost.app/funkwhale/data/" directory is missing and the expected "media", "music" and "static" directories are instead being placed in "/home/yunohost.app/funkwhale/" instead.
- Checking the config files in /var/www/funkwhale/config/.env, the paths are correct - ie "MUSIC_DIRECTORY_PATH=/home/yunohost.app/funkwhale/music" exists - which leads me to believe there's some config somewhere else pointing to the non-existent data directory.

### Logs

An example log of one of the (many) errors follows -

> 2021/08/15 11:53:43 [error] 16648#16648: *20440 open() "/home/yunohost.app/funkwhale/data/media/__sized__/attachments/d5/ed/79/mxv8sm-crop-c0-5__0-5-200x200-95.jpg" failed (2: No such file or directory), client: 180.181.55.30, server: audio.tryptophonic.com, request: "GET /media/__sized__/attachments/d5/ed/79/mxv8sm-crop-c0-5__0-5-200x200-95.jpg HTTP/2.0", host: "audio.tryptophonic.com", referrer: "https://audio.tryptophonic.com/"

**Comment by Didyme33** [comment]
Exactly the same problem here : based on nginx logs, when I try to play a song, it's trying to play from the the funkwhale/data directory, but when I upload a song it's been placed in the funkwhale/media directory...
Result : 404 error in the nginx logs, and Funkwhale stays silent.

**Comment by tryptophonic** [comment]
I can confirm that today's commit (22nd Nov) to the testing branch fixed the issue for me at least.
