### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by nin0-0** [YunoHost-Apps/funkwhale_ynh#154]
running `yunohost tools apps upgrade` gave an error, because he couldn't find python, so I put a symlink to /usr/bin/python3 on /usr/bin/python.

Then when upgrading it fails to reload fail2ban:

``` bash
Warning: Sep 05 08:59:43 systemd[1]: Reloading Fail2Ban Service.
Warning: Sep 05 08:59:43 fail2ban-client[15035]:  NOK: ("'FilterPyinotify' object has no attribute 'isAlive'",)
Warning: Sep 05 08:59:43 fail2ban-client[15035]: 'FilterPyinotify' object has no attribute 'isAlive'
Warning: Sep 05 08:59:43 systemd[1]: fail2ban.service: Control process exited, code=exited, status=255/EXCEPTION
Warning: Sep 05 08:59:43 systemd[1]: Reload failed for Fail2Ban Service.
```

I found such: https://github.com/fail2ban/fail2ban/issues/2646

this is the log: https://paste.yunohost.org/raw/uwojoyeres 
he can't find celery, dunno why

**Comment by yalh76** [comment]
Seems related to https://github.com/fail2ban/fail2ban/issues/2980 and fixed by now
