### ISSUE TITLE
How to get to the admin interface and federate? 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/funkwhale_ynh#16]
Hi
I can't find the admin interface? 
Further how can I add some other Funkwhale instance to my instance by federation? I am completely lost.  
And can my music folder in my home shared with Funkwhale, so that I can add music with nextcloud and it becomes available to Funkwhale?
Thanks for your help in advance.

**Comment by Jibec** [comment]
I had the same question about the admin link: https://code.eliotberriot.com/funkwhale/funkwhale/issues/202

I'll open a new issue for the music folder sync

**Comment by anmol26s** [comment]
The link to admin should be added to the readme. Have you tired federation on Funkwhale instances? How can I add it in the from admin interface? The admin interface is huge and complex.

**Comment by Jibec** [comment]
I had no opportunity to test the Federation of instances, for now I use it in standalone, I need to upgrade my own server before making it public.

You're correct, I'll improve readme.

About Federation, here is the documentation: https://docs.funkwhale.audio/federation.html

Kind remember: this is an alpha version, there is still a lot to improve in this app, the project dev will be happy to get your feedback :)

**Comment by EliotBerriot** [comment]
Hi @anmol26s and @Jibec!

Yeu should find documentation on how to access the admin interface in https://docs.funkwhale.audio/configuration.html#instance-settings

For your nextcloud music directory, you can try with https://docs.funkwhale.audio/importing-music.html#from-music-directory-on-the-server and a cronjob maybe ?

**Comment by anmol26s** [comment]
Hi @EliotBerriot 
Thanks for providing the links.
`python api/manage.py import_files "/srv/funkwhale/data/music/**/*.ogg" --recursive --noinput
`
FunkWhale only support .ogg or we can import .mp3 too?

**Comment by anmol26s** [comment]
Further I can't see any of the user or there music library to follow on other instances.
How can I find all these users on other instances to join there libraries 
![funkwhale_instances](https://user-images.githubusercontent.com/5068843/41678649-3639307c-74e9-11e8-862b-0e43ac66e0b8.png)
?

**Comment by EliotBerriot** [comment]
We support ogg, mp3 and flac files too.

**Comment by Jibec** [comment]
@anmol26s do you confirm Federation works fine for you?

**Comment by GannonTdW** [comment]
Hey,

I'm trying to add music that I have in my nextcloud.  She are in the follwing folder : `/home/yunohost.multimedia/share/Music/` 
So, I execute the following commands
```bash
cd /var/www/funkwhale
python api/manage.py import_files "/home/yunohost.multimedia/share/Music/*" --recursive --noinput
```
But I have the following error 
```
Traceback (most recent call last):
  File "api/manage.py", line 2, in <module>
    import django
ImportError: No module named django
```
I do not understand ... 
I saw that there is venv` in the install script, but 
```bash
# virtualenv /var/www/funkwhale/virtualenv
-bash: virtualenv: command not found
```
....

Did I miss something ?
@anmol26s  the only command worked for you ?

**Comment by anmol26s** [comment]
@EliotBerriot 
Hi
The link for federation is not available now. Can you please tell me how to add the libraries from the other instances if I don't know the users in that particular instance? If there is no place to find people from the instances then how will federation bloom?
