### ISSUE TITLE
Warning in diagnosis

### ISSUE THREAD

**Issue by shukon** [YunoHost-Apps/funkwhale_ynh#162]
### Describe the bug

Diagnosis gives me a warning:

<code>
An issue was found for app Funkwhale

This application is currently flagged as broken on YunoHost's application catalog. This may be a temporary issue while the maintainers attempt to fix the issue. In the meantime, upgrading this app is disabled.
</code>

I couldn't find anything about it in the forum, so I wondered if it's only me?

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.4.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: funkwhale_ynh 1.1.4~ynh2

### Steps to reproduce

:shrug: 

### Expected behavior

No warning flag I guess? Or rather some sort of announcement on what is happening.

### Logs

Not sure where I could find logs related to this problem.

**Comment by Thovi98** [comment]
It’s not a big problem, it’s due to a warning about the nginx configuration.
It will be resolved once https://github.com/YunoHost-Apps/funkwhale_ynh/pull/161 is merged in master :)

**Comment by shukon** [comment]
And indeed it is gone. Thank you so much for packaging this app :heart: .
