### ISSUE TITLE
Upgrade/install fail on arm architecture

### ISSUE THREAD

**Issue by Josue-T** [YunoHost-Apps/funkwhale_ynh#164]
### Describe the bug

App upgrade fail on arm.

### Context

- Hardware: BanaPi R2, (Armv7)
- YunoHost version: 4.3.6
- Previous app version: 1.1.4~ynh1

### Steps to reproduce

On arm board do:
    ```sh
    sudo yunohost app upgrade funkwhale
    ```

### Expected behavior

App upgrade should success but it fail.

### Logs

https://paste.yunohost.org/aqipezezet.bash

**Comment by yalh76** [comment]
That was temporary when python module cryptography wasn't available wheels and needed to be compiled from source. Now it's available

**Comment by Josue-T** [comment]
Hello,

I'have tested again and I still have the issue. On x86 the wheel package are available but not on armv7. On armv7 we must install rust to fix the issue. Or use a prebuilt package as I a do on the synapse package [here](https://github.com/YunoHost-Apps/synapse_python_build/releases)

**Comment by yalh76** [comment]
or maybe we can have a look at extracting from docker ^^ https://hub.docker.com/r/funkwhale/funkwhale/tags

**Comment by Josue-T** [comment]
If the version of the lib are same it could work. Because when we do this we must use a build for the exact same version of all dependencies. It's why I do a build for buster and bullseye.

**Comment by rosbeef** [comment]
Please change title to "Upgrade/install ... "

**Comment by Josue-T** [comment]
Hello,

Still have no support on ARM but marked as it support all architecture here: https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/manifest.toml#L23 :confused:

**Comment by Thovi98** [comment]
I'm sorry to not have looked at it sooner.
I will try to add ARM support soon, although I don't have such hardware so I will need testers 😇

**Comment by Thovi98** [comment]
Okay thanks! Will try this ASAP.
Do you recommend doing this on every hardware or only on ARM ?

**Comment by rosbeef** [comment]
It seems to be only an arm problem.
I can test your modification on my arm board.

**Comment by Josue-T** [comment]
I think it should be done with armhf or armel (armv6 and armv7).

**Comment by Thovi98** [comment]
Must be solved now, please reopen if not!
