### ISSUE TITLE
Need help with reverse proxying Funkwhale since it needs its own subdomain instead of subpath

### ISSUE THREAD

**Issue by minnixtx** [YunoHost-Apps/funkwhale_ynh#167]
### My YunoHost server

**Hardware:** RPi 4.
**YunoHost version:**  Official Pi image 4.3.6.2
**I have access to my server :** full access
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no 
**If yes, please explain:**

### Description of my issue
I'm not sure how yunohost actually handles other root domains other than its own main one. I installed funkwhale  but it needs its own root domain because of dependency issues instead of just a subpath so I created one within my DNS service (google domains) just as I did for yunohost. Also created one for funkwhale.mydomain.com within yunohost and chose that domain for funkwhale within the app interface on yunohost. My yuno instance is on an RPi 4 and every service I have installed currently works fine as it's just given a subpath within the yunohost root domain. I am running behind a nginx reverse proxy on another server within my LAN where SSL is terminated. My current nginx/sites-enabled conf for yunohost on the reverse proxy server looks like so:

```server {

   listen         443;
   listen    [::]:443;
   server_name    yuno.mydomain.com;

   location / {
        proxy_pass         https://192.168.57.203;
        proxy_redirect     off;
        proxy_read_timeout 60s;

        proxy_set_header          Host           yuno.mydomain.com;
        proxy_set_header          X-Real-IP       $remote_addr;
        proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;

        client_max_body_size 50M;
   }

   access_log /var/log/nginx/yunohost_access.log;
   error_log /var/log/nginx/yunohost_error.log error;
    ssl_certificate /etc/letsencrypt/live/yuno.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/yuno.mydomain.com/privkey.pem; # managed by Certbot

}

```
Everything is good on that end to access yunohost and its apps within its directories. How should my proxy conf look for yunohost applications that need their own domains? I tried creating another conf on the proxy server and changing 'server_name' to funkwhale.mydomain.com and leaving the rest the same but that didn't work. Any tips? Thanks

**Comment by yalh76** [comment]
you should ask ath the [YunoHost forum](https://forum.yunohost.org/) because it's not funkwhale specific
