### ISSUE TITLE
Login impossible / no django / raspberry

### ISSUE THREAD

**Issue by llinfrance** [YunoHost-Apps/funkwhale_ynh#17]
Hello,

I was able to install funkwhale on a raspberry pi on YunoHost 3.0.0.1 (stable), with some warnings only : 

> Warning: W: GPG error: http://cdn-fastly.deb.debian.org/debian jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
Warning: W: The repository 'http://httpredir.debian.org/debian jessie-backports InRelease' is not signed.
Warning: W: GPG error: http://cdn-fastly.deb.debian.org/debian jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
Warning: W: The repository 'http://httpredir.debian.org/debian jessie-backports InRelease' is not signed.
Warning: 2018-06-20 19:38:49 URL:https://code.eliotberriot.com/funkwhale/funkwhale/-/archive/0.14.2/funkwhale-0.14.2.tar.bz2 [7648609/7648609] -> "app.tar.bz2" [1]
Warning: 2018-06-20 19:38:55 URL:https://code.eliotberriot.com/funkwhale/funkwhale/-/jobs/4293/artifacts/download [3765294/3765294] -> "app-frontend.zip" [1]
Warning: Created symlink /etc/systemd/system/multi-user.target.wants/funkwhale__2-server.service → /etc/systemd/system/funkwhale__2-server.service.
Warning: Created symlink /etc/systemd/system/multi-user.target.wants/funkwhale__2-worker.service → /etc/systemd/system/funkwhale__2-worker.service.
Warning: Created symlink /etc/systemd/system/multi-user.target.wants/funkwhale__2-beat.service → /etc/systemd/system/funkwhale__2-beat.service.

After that, after login, it went shortly on the empty library, then switch back to the login page.

So I tried to import some files : 
`python api/manage.py import_files "/home/yunohost.multimedia/share/"  --recursive --noinput`
but I got : `ImportError: No module named django`

I hope this will help you :)

**Comment by Jibec** [comment]
well, you it's using a virtual env, you have to use `source` first, see an example:
https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/install#L146

**Comment by llinfrance** [comment]
Thank you for your answer ! So, I tried the same command in the virtualenv : 
`source virtualenv/bin/activate` then
`python api/manage.py import_files "/home/yunohost.multimedia/share/Music/*" --recursive --noinput`
Unfortunatly, I got : 

> Traceback(most recent call last):
  File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/environ/environ.py", line 271, in get_value
    value = self.ENVIRON[var]
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'FUNKWHALE_URL'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "api/manage.py", line 16, in <module>
    django.setup()
  File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/www/funkwhale/api/config/settings/production.py", line 14, in <module>
    from .common import *  # noqa
  File "/var/www/funkwhale/api/config/settings/common.py", line 44, in <module>
    FUNKWHALE_URL = env("FUNKWHALE_URL")
  File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/environ/environ.py", line 130, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/environ/environ.py", line 275, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the FUNKWHALE_URL environment variable

But is it expected to not be able to stay log in without any music ? The web interface log me out each time (with correct login/password).

**Comment by Jibec** [comment]
One issue, one problem.

Let's try to finish the CLI import, add this source also, after the first source for venv:

source $final_path/load_env

**Comment by llinfrance** [comment]
OK  for one issue, one problem (I though it was somehow related...)

So, I was able to do `source load_env` (removing $final_path because it was not known). Moreover, I change also the line in `load_env` file to remove $final_path...

I was then able to import an album successfully ! It finished with some errors though : 

> Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x75bee4b0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x75bee4b0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

**Comment by Jibec** [comment]
So, it works when you use the correct commands ;)

You can say thank you to Elliot (his login is one of the issue), and close this issue.

Ideally, you can use github' interface to edit the readme and submit a Pull Request, so other users know how to use the feature.

**Comment by EliotBerriot** [comment]
Hi @llinfrance, I'm glad you could make your import work! The ` File "/usr/lib/python3.5/weakref.py", line 117, in remove TypeError: 'NoneType' object is not callable` you see in your console comes from a small bug in your version of Python, but this should not affect Funkwhale. You can safely ignore those warnings :)

**Comment by Jibec** [comment]
I upgraded Reame in testing: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/33ddcba0256462cc5d1798eb921466669d13547e

Please let me know if anything else is needed

**Comment by llinfrance** [comment]
Thank you guys for your answer.
I did get this : 

> You can say thank you to Elliot (his login is one of the issue), and close this issue.

I was able to import some music, but I still cannot log in. Did I missed something you said, or should I open a new issue ?

By the way, sorry for such a late answer... When I will be able to log in I will comment on the cli import :)

**Comment by Jibec** [comment]
Well, at install you gave an admin user. Have you tried this and "funkwhale" as password?

**Comment by llinfrance** [comment]
Yes, this is the username and password I used. When I try something else it clearly said it is wrong.
Now, it just log in for less than a second then switch back to the login page.
For info, I am able to log on the admin page.
June 25, 2018 7:56 AM, "Jean-Baptiste" <notifications@github.com (mailto:%22Jean-Baptiste%22%20<notifications@github.com>)> wrote:
Well, at install you gave an admin user. Have you tried this and "funkwhale" as password?
