### ISSUE TITLE
Sharing Link results in HTML Error 405

### ISSUE THREAD

**Issue by Papillone** [YunoHost-Apps/funkwhale_ynh#177]
Hello,

I have done a fresh install of Funkwhale (1.2.4~ynh1) on Yunohost 4.3.6.3 .
Everything is working except the Sharing of Libraries. The Sharing Link results in HTML Error 405.

In the syslog there is this entry:
`gunicorn[4452]: 2022-05-08 07:43:36,845 django.request WARNING  Method Not Allowed: /federation/music/libraries/2b2d38e6-95f1-4bf1-a75c-ce0b8ed54942`

Any hints for me?

Papillone

**Comment by yalh76** [comment]
Seem that the link doesn't be used directly but following https://docs.funkwhale.audio/develop/user_documentation/libraries/follow_library.html
