### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/funkwhale_ynh#18]
Hi
The app don't get forced to https.
```
if ($scheme = http) {
        rewrite ^ https://$server_name$request_uri? permanent;
    }
```
is missing in the nginx.

**Comment by Jibec** [comment]
I'm unsure this really changes anything, behavior is the same on my server, please test this and confirm Federation still works as expected: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/ebb38edc3f3d368f8fab981c45340833aff422ea

**Comment by SohKa** [comment]
Hello,
The situation is still the same. And I can confirm adding the `rewrite` parameter fixes the issue.
Did you get confirmation that this breaks Federation ? If necessary, I'll test it.

**Comment by SohKa** [comment]
Sorry, I haven't made enough research.

It seems you merged the fix in master (as we can see in the commit you mentioned). But it has been removed by this commit d84761e. The author, Pierrick, isn't reachable on Github. It would have been nice if he could elaborate why he did this change.

@Jibec, do you think you could retrofit the `rewrite` ? I can write the PR if it makes the work a bit easier to you.
