### ISSUE TITLE
Peer authentication failed for user "funkwhale" then e_sendauth: no password supplied

### ISSUE THREAD

**Issue by chupinmaxime** [YunoHost-Apps/funkwhale_ynh#180]
I tried to create my superuser in /srv/funkwhale/
```
python api/manage.py createsuperuser
```
after the script automatic install (`sudo sh -c "$(curl -sSL https://get.funkwhale.audio/)"`) but without nginx because I want to use apache2. 

I got firt the error `Peer authentication failed for user "funkwhale"` then I modified the `/etc/postgresql/12/main/pg_hba.conf
` to change `local all all peer` to `local all all password` but then I got the error `psycopg2.OperationalError: fe_sendauth: no password supplied`. I do not find what to do. 

Thanks

**Comment by yalh76** [comment]
you should not try to auto-install using upstream app on YunoHost ...........
