### ISSUE TITLE
pip version in Yunohost 11

### ISSUE THREAD

**Issue by Vitriia** [YunoHost-Apps/funkwhale_ynh#187]
### Describe the bug

After upgrading Yunohost to Yunohost 11 (debian 11), Funkwhale stopped to work. All Funkwhale services are on exited status.

It seams to be because the virtualenv pip version is outdated/broken.
```
# /var/www/funkwhale/virtualenv/bin/pip
Traceback (most recent call last):
  File "/var/www/funkwhale/virtualenv/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

This funkwhale [GitLab solution ](https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1562)isn't working

```
sudo -u funkwhale -H -E python3 -m pip update /var/www/funkwhale/virtualenv
ERROR: unknown command "update"
```

No clue on what i can do next
### Context

Funkwhale 1.2.7~ynh1

> yunohost: 
>   repo: stable
>   version: 11.0.9.9
> yunohost-admin: 
>   repo: stable
>   version: 11.0.10
> moulinette: 
>   repo: stable
>   version: 11.0.9
> ssowat: 
>   repo: stable
>   version: 11.0.9

### Steps to reproduce

Perform the Yunohost migration to Yunohost 11.

### Expected behavior

Services not stopping

### Logs
sudo yunohost service log funkwhale-server
```
  - août 23 13:37:33 systemd[1]: Started funkwhale application server.
  - août 23 13:37:33 gunicorn[98338]: Traceback (most recent call last):
  - août 23 13:37:33 gunicorn[98338]:   File "/var/www/funkwhale/virtualenv/bin/gunicorn", line 5, in <module>
  - août 23 13:37:33 gunicorn[98338]:     from gunicorn.app.wsgiapp import run
  - août 23 13:37:33 gunicorn[98338]: ModuleNotFoundError: No module named 'gunicorn'
  - août 23 13:37:33 systemd[1]: funkwhale-server.service: Main process exited, code=exited, status=1/FAILURE
  - août 23 13:37:33 systemd[1]: funkwhale-server.service: Failed with result 'exit-code'.
```

sudo yunohost service log funkwhale-beat
```
  - août 23 13:37:06 systemd[1]: Started funkwhale celery beat process.
  - août 23 13:37:06 celery[98246]: Traceback (most recent call last):
  - août 23 13:37:06 celery[98246]:   File "/var/www/funkwhale/virtualenv/bin/celery", line 5, in <module>
  - août 23 13:37:06 celery[98246]:     from celery.__main__ import main
  - août 23 13:37:06 celery[98246]: ModuleNotFoundError: No module named 'celery'
  - août 23 13:37:06 systemd[1]: funkwhale-beat.service: Main process exited, code=exited, status=1/FAILURE
  - août 23 13:37:06 systemd[1]: funkwhale-beat.service: Failed with result 'exit-code'.
```

sudo yunohost service log funkwhale-worker
```
  - août 23 13:37:21 systemd[1]: Started funkwhale celery worker.
  - août 23 13:37:21 celery[98291]: Traceback (most recent call last):
  - août 23 13:37:21 celery[98291]:   File "/var/www/funkwhale/virtualenv/bin/celery", line 5, in <module>
  - août 23 13:37:21 celery[98291]:     from celery.__main__ import main
  - août 23 13:37:21 celery[98291]: ModuleNotFoundError: No module named 'celery'
  - août 23 13:37:21 systemd[1]: funkwhale-worker.service: Main process exited, code=exited, status=1/FAILURE
  - août 23 13:37:21 systemd[1]: funkwhale-worker.service: Failed with result 'exit-code'.
```

**Comment by Thovi98** [comment]
Did you already tried to force upgrade Funkwhale after the upgrade? Sometimes, it’s necessary : `sudo yunohost app upgrade funkwhale -F` (or `-f` i’m not sure)

**Comment by Vitriia** [comment]
Hi, i didn't know you can force upgrades. I will try it on my save and post the results

(i have corrected the issue 2 days ago but it's ugly as hell and not a real solution : 
- Backuping the app. 
- Removing it
- Making a fresh new install
- Copy the virtualenv/bin folder somewhere
- Remove the fresh install
- Restore the previous install
- Erase virtualenv/bin with the fresh install copy)

**Comment by yalh76** [comment]
well if it works for you, fine
