### ISSUE TITLE
jessie-backports is not signed

### ISSUE THREAD

**Issue by llinfrance** [YunoHost-Apps/funkwhale_ynh#19]
During the funkwhale install, a backport is added : 
https://github.com/YunoHost-Apps/funkwhale_ynh/blob/9719aa0614b7052ec39bf15f5771e4676d0a4ce6/scripts/install#L73

This backport then produce some warnings after `apt-get update` which is not reassuring for unexperimented user like me :) 
> W: GPG error: http://cdn-fastly.deb.debian.org/debian jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
W: The repository 'http://httpredir.debian.org/debian jessie-backports InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I am using a raspberry pi on stretch (yunohost 3.0).

**Comment by Jibec** [comment]
strange to have jessie backports in stretch, here is a potential fix: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/3d10632f6c4240811e96ab6744bef403c6319e73

**Comment by llinfrance** [comment]
Hello,

This fix solved half of the issue. It is now a stretch backport : 

> Warning: W: GPG error: http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
Warning: W: The repository 'http://httpredir.debian.org/debian stretch-backports InRelease' is not signed.
Warning: W: GPG error: http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
Warning: W: The repository 'http://httpredir.debian.org/debian stretch-backports InRelease' is not signed.

But it is still not-signed and blocked `apt-get update` from cli : (this block also system update in the admin interface) 

> Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease                                                          
Hit:3 http://forge.yunohost.org/debian stretch InRelease                                                               
Get:4 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease [91.8 kB]                   
Ign:4 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease
Fetched 91.8 kB in 2s (41.8 kB/s)
Reading package lists... Done
W: GPG error: http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
W: The repository 'http://httpredir.debian.org/debian stretch-backports InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

In the installation script, it is written that backport is required for ffmpeg, but this package is available in the [stretch stable branch](https://packages.debian.org/stretch/ffmpeg). Maybe there is something I missed ?

Cheers !

**Comment by Jibec** [comment]
That's true, I'll fix it in next release, thanks for point it.
