### ISSUE TITLE
`funkwhale-server` times out on startup

### ISSUE THREAD

**Issue by orhtej2** [YunoHost-Apps/funkwhale_ynh#206]
_This issue is more of conversation starter._

On my garbage-tier Kimsurfi VPS with `Intel(R) Atom(TM) CPU D425   @ 1.80GHz` CPU `funkwhale-server` service fails to start due to timeout.
After modifying [service definition](https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/conf/funkwhale-server.service) to include `--timeout 120` (as per [gunicorn docs](https://docs.gunicorn.org/en/stable/settings.html#timeout)) it works as expected (starts successfully and funkwhale works just fine), but the solution is, as I understand, anti-recommended by gunicorn team (see below) so I'm not sure if it's fit for general use.

> Generally, the default of thirty seconds should suffice. Only set this noticeably higher if you’re sure of the repercussions for sync workers.

Should ynh integration include such workaround? If not is there a way to improve the startup performance?

**Comment by Thovi98** [comment]
This would be to be set only in `funkwhale-server.service` or also in the other services?
Do you now any disadvantage to set this?

After a quick search, I’m in favour of this. I will wait for your answer before proceeding though.
