### ISSUE TITLE
Level 4 forced to one

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/funkwhale_ynh#21]
For level 4 in YunoHost, the application have to support "ldap and HTTP AUTH".
This is not possible for now as the feature doesn't exist.
Ping @EliotBerriot

**Comment by EliotBerriot** [comment]
Thanks for the ping, I've opened an issue to keep a track of that: https://code.eliotberriot.com/funkwhale/funkwhale/issues/335

**Comment by PierrickBrun** [comment]
Looks like the issue is fixed on funkwhale's side. Can we re-open it ?

**Comment by Jibec** [comment]
That's true, it should be soon an old remember: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/3e44180708dddbef360e25841b9cf7be6e144c95
