### ISSUE TITLE
Can't register new user

### ISSUE THREAD

**Issue by ademant** [YunoHost-Apps/funkwhale_ynh#217]
### Describe the bug

On Yunohost I assigned domain (funkwhale.domain.tld) and changed the DNS file at Hetzner as suggested. For this domain the sending and receiving of e-mails are permitted.
The funkwhale app (Version 1.2.10~ynh3 ) is installed.

When registering a new user, it is said that a mail is sent to the user. But the user does not get any mail and can not verify the mail address.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.1.18
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Expected behavior

I should be able to enregister a new user, which can login to funkwhale.

**Comment by Thovi98** [comment]
Aren't the sent emails categorized as spam?

And are you sure that sending and receiving of emails are permitted?
Did you try to set a smtp relay in the Yunohost settings?

**Comment by ademant** [comment]
On yunohost I installed roundcube and tested sending and receiving e-mails to/from gmx.net: It's working.

I tried several things: Using an external e-mail address (gmx) and found nothing in inbox or spam. Then I used above mail address on yunohost (which works to send/receive to gmx.net) for registering on funkwhale. No mail in this account.

Also I read the documentation of yunohost/funkwhale and funkwhale itself: I have no idea, where to change settings for mail server/relay.
So for your last question: I have not consider this, because I have no idea how to change mail settings.

**Comment by ademant** [comment]
Finally I found the reason:
Funkwhale does not send E-Mails, but print to stdout.
The config file /var/www/funkwhale/config/.env had no working smtp config.
After I added following line, the registration of new users worked (and restart of funkwhale-server):

EMAIL_CONFIG=smtp://localhost:25

(I also changed /etc/yunohost/apps/funkwhale/conf/env.prod )

**Comment by Thovi98** [comment]
I don’t use the email in Funkwhale, so I never encountered this.
Thanks for your heads up! I will update it.
