### ISSUE TITLE
Change of maintainer

### ISSUE THREAD

**Issue by Sporiff** [YunoHost-Apps/funkwhale_ynh#225]
Hi everyone!

As you've probably noticed, I've not had much interaction with this repository for a while as I've been busy working on the upstream code (and my day job!). As my workload increases, I'm going to have less and less time to focus on this deployment.

Since @Thovi98 has done the lion's share of the work on this package in recent months, I think it makes more sense for them to be listed as the principle maintainer to put credit where it's due, if they're willing to put their name on it.

I'm really appreciative of the work that's gone in to keeping this package available for Yunohost users 🙏 I will continue to offer support upstream where I can and to communicate changes that might affect downstream packages.

**Comment by Thovi98** [comment]
Hello @Sporiff !

I completely understand your message! Thanks for all you have done and do for Funkwhale (the documentation is incredible now!).
Thanks also for your packaging in Funkwhale for Yunohost (especially for packaging Funkwhale 1.0, it was a great work).

As you asked, I’m willing to put my name as new maintainer. I will update it with the 1.3.0 release (btw just tested on my server, it’s awesome! It’s way more responsive than previously!)

Looking forward to see where Funkwhale will go 🚀
