### ISSUE TITLE
YunoHost documentation link for this app link produces a strange HTTP error

### ISSUE THREAD

**Issue by jahway603** [YunoHost-Apps/funkwhale_ynh#228]
### Describe the bug

Navigating to https://yunohost.org/app_funkwhale produces the following error message:

```
Server Error
Sorry, something went terribly wrong!

E_NOTICE - Trying to access array offset on value of type bool
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

### Context

N/A

### Steps to reproduce

N/A

### Expected behavior

The link would display correctly

### Logs

N/A

**Comment by yalh76** [comment]
It's because no one has already written a documentation for funkwhale on yunohost website

**Comment by orhtej2** [comment]
@yalh76 that's not true: https://github.com/YunoHost/doc/tree/master/pages/04.applications/10.docs/funkwhale

**Comment by Thovi98** [comment]
It's fixed (see https://forum.yunohost.org/t/faulty-links-in-yunohost-web-documentation/25197/2)
