### ISSUE TITLE
android app does not connect to instance

### ISSUE THREAD

**Issue by ballinger** [YunoHost-Apps/funkwhale_ynh#240]
### Describe the bug

funkwhale android app stable and dev version cannot connect to instance.

### Context

- Hardware: x64
- YunoHost version: 11.2.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
nfs server
- Using package version/branch: 1.3.1

### Steps to reproduce

type server address into FW android app and press login

### Expected behavior

connection to server

### Logs
funkwhale-server
`-- Journal begins at Sat 2023-07-15 18:21:46 CEST, ends at Mon 2023-07-24 12:01:20 CEST. --
Jul 24 11:59:31 gunicorn[84831]:     self.disconnect(message["code"])
Jul 24 11:59:31 gunicorn[84831]:   File "/var/www/funkwhale/api/funkwhale_api/common/consumers.py", line 22, in disconnect
Jul 24 11:59:31 gunicorn[84831]:     groups = self.scope["user"].get_channels_groups() + self.groups
Jul 24 11:59:31 gunicorn[84831]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
Jul 24 11:59:31 gunicorn[84831]:     return func(self._wrapped, *args)
Jul 24 11:59:31 gunicorn[84831]: AttributeError: 'AnonymousUser' object has no attribute 'get_channels_groups'
Jul 24 12:00:31 gunicorn[84833]: [2023-07-24 10:00:31 +0000] [84833] [INFO] ('192.168.1.102', 0) - "WebSocket /api/v1/activity" 403
Jul 24 12:00:31 gunicorn[84833]: [2023-07-24 10:00:31 +0000] [84833] [INFO] connection failed (403 Forbidden)
Jul 24 12:00:31 gunicorn[84833]: [2023-07-24 10:00:31 +0000] [84833] [INFO] connection closed
Jul 24 12:00:31 gunicorn[84833]: [2023-07-24 10:00:31 +0000] [84833] [ERROR] Exception in ASGI application
Jul 24 12:00:31 gunicorn[84833]: Traceback (most recent call last):
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 238, in run_asgi
Jul 24 12:00:31 gunicorn[84833]:     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
Jul 24 12:00:31 gunicorn[84833]:     return await self.app(scope, receive, send)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/routing.py", line 62, in __call__
Jul 24 12:00:31 gunicorn[84833]:     return await application(scope, receive, send)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
Jul 24 12:00:31 gunicorn[84833]:     return await self.inner(dict(scope, cookies=cookies), receive, send)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/sessions.py", line 263, in __call__
Jul 24 12:00:31 gunicorn[84833]:     return await self.inner(wrapper.scope, receive, wrapper.send)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/auth.py", line 185, in __call__
Jul 24 12:00:31 gunicorn[84833]:     return await super().__call__(scope, receive, send)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/middleware.py", line 24, in __call__
Jul 24 12:00:31 gunicorn[84833]:     return await self.inner(scope, receive, send)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/routing.py", line 116, in __call__
Jul 24 12:00:31 gunicorn[84833]:     return await application(
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
Jul 24 12:00:31 gunicorn[84833]:     return await consumer(scope, receive, send)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
Jul 24 12:00:31 gunicorn[84833]:     await await_many_dispatch(
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/utils.py", line 50, in await_many_dispatch
Jul 24 12:00:31 gunicorn[84833]:     await dispatch(result)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/asgiref/sync.py", line 479, in __call__
Jul 24 12:00:31 gunicorn[84833]:     ret: _R = await loop.run_in_executor(
Jul 24 12:00:31 gunicorn[84833]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Jul 24 12:00:31 gunicorn[84833]:     result = self.fn(*self.args, **self.kwargs)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/db.py", line 13, in thread_handler
Jul 24 12:00:31 gunicorn[84833]:     return super().thread_handler(loop, *args, **kwargs)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/asgiref/sync.py", line 538, in thread_handler
Jul 24 12:00:31 gunicorn[84833]:     return func(*args, **kwargs)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/consumer.py", line 125, in dispatch
Jul 24 12:00:31 gunicorn[84833]:     handler(message)
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/channels/generic/websocket.py", line 105, in websocket_disconnect
Jul 24 12:00:31 gunicorn[84833]:     self.disconnect(message["code"])
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/api/funkwhale_api/common/consumers.py", line 22, in disconnect
Jul 24 12:00:31 gunicorn[84833]:     groups = self.scope["user"].get_channels_groups() + self.groups
Jul 24 12:00:31 gunicorn[84833]:   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
Jul 24 12:00:31 gunicorn[84833]:     return func(self._wrapped, *args)
Jul 24 12:00:31 gunicorn[84833]: AttributeError: 'AnonymousUser' object has no attribute 'get_channels_groups'`

**Comment by stilobique** [comment]
Don't know if I can help, but check in your web admin > `Users` > `Manage groups and permissions` > in your Visitor section, look if Funkwhale are listed.

**Comment by ballinger** [comment]
nice - thank you! that did the trick. also seems the funkwhale app does not like the brave browser, stuck in some redirect loop after auth. default chrome browser works tough.
