### ISSUE TITLE
Installation: funkwhale.mydomain.com => mydomain.com/funkwhale = possible ?

### ISSUE THREAD

**Issue by Drolsquito** [YunoHost-Apps/funkwhale_ynh#27]
Hi, instead of installing funkwhale on a domain like _funkwhale.mydomain.com_, would it be possible to have the option to install it on _mydomain.com/funkwhale_ ? Most of yunohost apps allow it, even to change app url once installed.

The reason I ask this is because I upgraded to yunohost 3 specially for funkwhale but I can't install it because some routers like mine have issues; all the apps installed in mydomaine.com/appname work, but the ones installed on appname.mydomain.com don't.

Would be great that option when installing, thank you.

**Comment by Jibec** [comment]
hi, thanks for taking time to write this issue, but is this is an upstream issue, this feature doesn't exist.
You can ask for it there: https://code.eliotberriot.com/funkwhale/funkwhale/
