### ISSUE TITLE
Unable to install funkwhale: An error occurred inside the app installation script

### ISSUE THREAD

**Issue by ChildishGiant** [YunoHost-Apps/funkwhale_ynh#281]
### Describe the bug
When attempting to install I got an error that appears to be in the last stages of installing: `django.db.utils.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "funkwhale"`

### Context

- Hardware: HPE ProLiant ML310e Gen8 v2 Server (Old tower server from ebay)
- YunoHost version: 12.0.9.1
- I have access to my server: through the webadmin and direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: trying to install 

### Steps to reproduce
   1. https://youryunohostinstance.tld/admin/#/apps/install/funkwhale
   2. Attempt to install

### Expected behavior
Install to work

### Logs
https://paste.yunohost.org/raw/ogucileyiw

**Comment by Thovi98** [comment]
It should be managed by the Yunohost core… Could you please try to regenconf postgresql by yunohost tools regen-conf postgresql --with-diff and see if it changes peer to md5?

And what do you have in your /etc/postgresql/ directory?

**Comment by ChildishGiant** [comment]
I ran `yunohost tools regen-conf postgresql --with-diff` and it outputted nothing but didn't error. Tried again and it's all magically working  🧙🏻🪄

**Comment by fccl-vandoeuvre** [comment]
Hello,

I've just installed a Yunohost server to experiment with Funkwhale for a 2027 project, and I've encountered the same problem. The indicated command solves the error. Perhaps it would be useful to highlight this solution in the documentation?

Axel.
