### ISSUE TITLE
Import in-place

### ISSUE THREAD

**Issue by llinfrance** [YunoHost-Apps/funkwhale_ynh#31]
Hello everybody,

In order to be able to add some music with CLI with the --in-place option, I had to change this line in config/.env : 
`MUSIC_DIRECTORY_PATH=/music`
to 
`MUSIC_DIRECTORY_PATH=/var/www/funkwhale/data/music`
as it is mention in the documentation [here](https://docs.funkwhale.audio/importing-music.html#from-music-directory-on-the-server). The CLI then work properly.
Then, I had to do `systemctl restart funkwhale.target` in order to play the added music.

(I do not have the knowledge to change the install script in order to make PR for this change.)

Finally, should it be more useful to use this path instead ?
`/home/yunohost.multimedia/share/Music`

**Comment by Jibec** [comment]
Hi, thanks for sharing this. I'll correct the scripts.

No, I won't use multimedia files for now. I see it is in discussion for including it in core. Once done (I assume it will come in 3.3) I'll spend the time to add this feature.

I'm not in a hurry for this feature as the application is still in beta, works fine and I don't want to increase maintenance.

**Comment by anmol26s** [comment]
If multiple locations can be used then adding  `/home/yunohost.multimedia/share/Music`. Bu then Funkwhale wants proper formatted meta-data and the  /home/yunohost.multimedia/share/Music can have music files with no meta-data at all and this could result in error.
