### ISSUE TITLE
FATAL:  authentification peer échouée pour l'utilisateur « funkwhale »

### ISSUE THREAD

**Issue by samvermeulenpro** [YunoHost-Apps/funkwhale_ynh#38]
Hi,
installation master or testing branch fails with Yunohost 3.2 / Debian 9.5 :

Logs : https://paste.yunohost.org/raw/ocezuhuteg

Thanks

**Comment by Jibec** [comment]
hi, what other application do you have?
It is weird that you have "peer" usage for postgres.

Go in /etc/postgresql/9.6/main/pg_hba.conf
`local all all peer` by `local all all password`.

Then install again

**Comment by samvermeulenpro** [comment]
It's working 👍 

thank you very much
