### ISSUE TITLE
Add fail2ban rules

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/funkwhale_ynh#47]
as pointed by @anmol26s , we need to add fail2ban rules

This is the helper:
https://github.com/YunoHost-Apps/shaarli_ynh/blob/testing/scripts/_common.sh#L16-L78

Here is an example:
https://github.com/YunoHost-Apps/shaarli_ynh/blob/testing/scripts/install#L136

our discussion: https://github.com/YunoHost-Apps/funkwhale_ynh/pull/37#issuecomment-433624563 anmol26s

**Comment by anmol26s** [comment]
This configuration works for me:
`ynh_add_fail2ban_config "/var/log/nginx/$domain-access.log" "<HOST>.* "POST /api/v1/token/ HTTP/1.1" 400 68.*$" 5`

**Comment by Jibec** [comment]
thank you, you should be able to test with this commit: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/729d71536fe78e0d18cc777960e3d2045a4fe9fe
