### ISSUE TITLE
Services & Logs missing from services list

### ISSUE THREAD

**Issue by rushsteve1** [YunoHost-Apps/funkwhale_ynh#49]
The Funkwhale related services and their logs are missing from the YunoHost dashboard services list.

It would be useful to have them there so that we can view logs for issues and generally manage the services better.

**Comment by Jibec** [comment]
fixed by https://github.com/YunoHost-Apps/funkwhale_ynh/commit/8e470c76defd41aa6e67dcb0897471958d5d0e30
