### ISSUE TITLE
Impossible to import music - youtube and mp3

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/funkwhale_ynh#5]
Hello

1. I have tried to import music with youtube-dl but the service funkwhale-worker show errors and the music is never imported

https://paste.yunohost.org/soleyijafo.coffeescript

2. I have tried to import music manually with mp3 files but I get errors related to TAG not found

https://paste.yunohost.org/foweyuzobi.go

**Comment by Jibec** [comment]
hi, both use cases works here, but I agree the youtube download interface could be improved!

about youtube:

1. connect to the technical interface: domain.tld/api/admin/
2. go to **Global preferences**
3. edit the "YouTube API key" with your API key. Yes, you have to create one on: https://console.developers.google.com the name of the key to create is "YouTube Data API v3"
4. come back to the "import" page
5. use the musicbrainz search field to find what you're looking for (artist, album or whatever), then click next to see the youtube search result. For each result, when you clic on "import this release", you'll see images and "download url"

thanks for testing this :)
please remember funkwhale is a really young, do not hesitate to file bug and suggestions there: https://code.eliotberriot.com/funkwhale/funkwhale/
