### ISSUE TITLE
Is opening of the port required?

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/funkwhale_ynh#50]
Hi
As the Funkwhale and Nginx are on same server, do we need to open the port for the outer web?
https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/install#L66

Most of the time we don't need to open the port and it can be security concern.

**Comment by EliotBerriot** [comment]
From Funkwhale's perspective there is indeed no need to have this exposed to the outside world, and as you guessed, it raises potential security concerns, so I assume we can safely remove it @Jibec

**Comment by Jibec** [comment]
hello, should be fixed by this: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/c22807493ed23582bc9770d765a69cc1fb337953
