### ISSUE TITLE
Cache setting should not be done in domain.conf

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/funkwhale_ynh#51]
Hi 
I hope you are doing good.
I tried to upgrade funkwhale and it failed along with the restore failure too. The cache lines you are trying to enter at /etc/nginx/conf.d/domain.tld.conf is giving error. 
https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/install#L114-L124

Cache setting should not be done in /etc/nginx/conf.d/domain.tld.conf because every time yunohost gets updated this files is forced to get the setting of yunohost nginx template which will keep braking the app on every yunohost update.

Best solution is to put the cache file by creating a new file /etc/nginx/conf.d/$app-cache.conf and insert the lines here. Its easy to manage and will also not break yunohost every time new yunohost version is pushed.

Thanks

**Comment by Jibec** [comment]
I tried but it failed, I'll try again, maybe I can use some hook

**Comment by anmol26s** [comment]
I did it for Pleroma, but I don't maintain this app. This is only for reference.

https://github.com/YunoHost-Apps/pleroma_ynh/blob/master/scripts/install#L148-L158

**Comment by Jibec** [comment]
I don't remember which command was creating an issue between map and cache. Hopefully I'll find a workaround for map too.

Any reason to use two separate nginx file?

**Comment by anmol26s** [comment]
> Any reason to use two separate nginx file?
You can do it without separate file. Actually I should have done it without a without a separate file too. :)

**Comment by Jibec** [comment]
should be fixable, see mastodon's discussion https://mamot.fr/web/statuses/101630160001582166

**Comment by Jibec** [comment]
from #86 we don't have any manual edit of nginx file
