### ISSUE TITLE
load_env path

### ISSUE THREAD

**Issue by bachy** [YunoHost-Apps/funkwhale_ynh#53]
I think the install script is missing some string replacement.

in /var/www/funckwhale/code/load_env, ```${final_payh}``` should be replaced by ```/var/www/funkwhale```

that's what i did to be able to load the virtualenv and run import_files
https://forum.yunohost.org/t/funkwhale-ajout-des-dossiers-yunohost-multimedia-dans-funkwhale-add-yunohost-multimedia-in-funkwhale/5990/3

**Comment by Jibec** [comment]
Hello, thanks for your report.
The bug as been fixed and is available in the "testing" branch, would you mind confirm the good behavior?

https://github.com/YunoHost-Apps/funkwhale_ynh/commit/0c4026699186df47e80058c370044ac2a507f9e2
