### ISSUE TITLE
Update to 0.18

### ISSUE THREAD

**Issue by PierrickBrun** [YunoHost-Apps/funkwhale_ynh#56]
Version 0.18 was released this morning, I've created the issue to document the update.

Here is the changelog : https://docs.funkwhale.audio/changelog.html#naomi-2019-01-22 , there are changes to the nginx template to do. and a suggested script to run.

**Comment by Jibec** [comment]
Bonjour Pierrick, suite à notre échange sur Mastodon, la première étape pour être capable d'aider, c'est de savoir tester, voici comment le procède: https://forum.yunohost.org/t/outils-pour-packager-une-application/3731/2

Le seul point à mettre à jour, c'est que nous sommes maintenant en Debian 9, donc l'adresse pour les ISO est la suivante : https://cdimage.debian.org/cdimage/archive/9.6.0/amd64/iso-cd/

Si tu réussis à tester, alors tu peux procéder de la sorte:

* mets à jour les fichiers à télécharger https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/conf/app-frontend.src et https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/conf/app.src
* modifie le fichier Nginx: https://docs.funkwhale.audio/changelog.html#iframe-widget-to-embed-public-tracks-and-albums-manual-action-required
* ne suis aucune des autres recommandations et teste si ça fonctionne

Si et seulement si ça fonctionne, tu pourras ajouter https://docs.funkwhale.audio/changelog.html#delete-pre-0-17-federated-tracks-manual-action-suggested et https://docs.funkwhale.audio/changelog.html#automatically-load-env-file

Puis enrichir le fichier de tests automatique https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/check_process pour qu'il teste également depuis le dernier commit : 8b7b3f0806c9f3600a0900bcae8e9f25a3e29f91

Tu peux écrire en français ici, aucun soucis

**Comment by PierrickBrun** [comment]
Merci pour les conseils, j'ai pu installer mon environnement de dev et commencer à tester. J'ai fait une branche sur mon fork pour travailler dessus, pour l'instant ça ne marche pas mais j'ai l'impression d'avancer.
Je fais une PR dès que ça m'a l'air OK.

**Comment by Jibec** [comment]
Super, souviens toi que tu dois d'abord faire un fork de ce dépôt et travailler chez toi. Puis pousser ton travail sur github. Puis c'est via github que tu feras la PR.

Tu n'as pas à attendre d'avoir quelque choses de parfait pour ouvrir cette PR, déjà ça te réduira la pression et quelqu'un passant par ici verra que tu travailles dessus.

Amuse toi bien, je suis dispo ici ou sur Mastodon.
-- 
Jean-Baptiste Holcroft
