### ISSUE TITLE
Failed installation (Logs)

### ISSUE THREAD

**Issue by IsidoreIsou** [YunoHost-Apps/funkwhale_ynh#60]
Hello,
(I've asked for help on yunohost forum as well, will update both threads)

I was able to install Funkwhale on a home YNH server, now I’m trying to install it on a VPS (Kimsufi) but the installation is failing. It’s on a separate domain. My YNH installation is clean.

Here is the log : https://paste.yunohost.org/raw/zebunoxovi

Thanks for your help!

**Comment by GannonTdW** [comment]
hello, 

have you `postgresql-contrib` ?
```
dpkg -l |grep postgresql-contrib
```
If not : 
```bash
apt install postgresql-contrib
```
cf [here](https://forum.yunohost.org/t/funkwhale-install-fail/5754)

Same message as on the Yunohost forum :)

**Comment by IsidoreIsou** [comment]
Problem solved! Installation runs without error after 

`apt install postgresql-contrib`
