### ISSUE TITLE
Removed media dir after backup restore

### ISSUE THREAD

**Issue by EliotBerriot** [YunoHost-Apps/funkwhale_ynh#66]
Hi there, I'm opening this ticket on behalf of [marsxyz](https://sale.gauchiste.club/users/marsxyz), since they lack the time to do so right now.

It seems Funkwhale's YunoHost package deletes existing media files when restoring a backup, which effectively prevent anything from playing afterward. The issue was spotted during an upgrade that went wrong, when trying to restore a backup. (Marsxyz had a separate backup, so the underlying data is not lost.)

I'm not exactly sure why, and hopefully marsxyz will share more details, but it may be related to the fact that media/music files are stored under the `code/data` directory. Since media files are not backed-up (because they're huge), maybe restoring `code/` simply result in deleting the data dir? This is a purely hypothetical guess, maybe there is another reason.

**Comment by Jibec** [comment]
yep, we need the feedback for marsxyz to understand. On upgrade, there is indeed no backup of media files and I changed code organization a few months ago. So I need to know when was the backup done and when was the upgrade done, and what failed to reproduce the issue. All these information are in /var/log/yunohost

I'll ping him to have a feedback. Thanks.
