### ISSUE TITLE
Import Cli Permission Error

### ISSUE THREAD

**Issue by stilobique** [YunoHost-Apps/funkwhale_ynh#68]
Hi,
i'm try to import my music with the __import-cli__ function, i'm before any difficulte. I'm resole the first error (```No module named django```) with the env. loaded ([more information on Yunohost forum](https://forum.yunohost.org/t/funkwhale-ajout-des-dossiers-yunohost-multimedia-dans-funkwhale-add-yunohost-multimedia-in-funkwhale/5990)).

Now the terminal send me a permission error, i'm adding the chown update (funkwhale user and group) but same problem. `PermissionError [Errno 13] Permission denied` . 

I'm create a symbolic link from a new hard drive mount on `/media/storage/musics`

**Comment by Jibec** [comment]
this is not supported by this package. Please wait for this feature to be added: https://github.com/YunoHost-Apps/funkwhale_ynh/issues/15
