### ISSUE TITLE
Random "Network error" on music import

### ISSUE THREAD

**Issue by IsidoreIsou** [YunoHost-Apps/funkwhale_ynh#69]
Hello,

This is an error I've had since I started using FW on YNH.
* When importing files from the wep page, I randomly got a `network` error, on one or more specific file. And importing _this file_ again create the same error. It's like some files are doomed and won't pass the importation.
* It's not size related, I can import large file without issues.
* All my music is tagged with Picard and perfectly recognized by FW.
* My YNH is a dedicated servers (Kimsufi), 100 Mbps, I import from a solid Ethernet connection. Same error using wifi and from other geographical locations.

![](https://framapic.org/nJTA6vjOrFWd/aPoymSiXNzlB)

Can you please help me finding a log to know what happens ? I've looked in `YNH admin > App > FW > Logs` but nothing there.

Thanks!

**Comment by Jibec** [comment]
you may find the answer in /var/log/funkwhale, see: https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/install#L230:L232

**Comment by Jibec** [comment]
please open again this issue if you still have the issue
