### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/funkwhale_ynh#7]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/funkwhale%20(Community)/4/console

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by Jibec** [comment]
whatever you like, I don't care about this administrative way of classifying things, manifest is explicit, this is Debian Stretch work
