### ISSUE TITLE
Raven error reporting not cleanly managed

### ISSUE THREAD

**Issue by Josue-T** [YunoHost-Apps/funkwhale_ynh#73]
Hello,

Seeing the config file I discovered that in the config file is not well cleanly implemented. Here is the content which I found that is not really clean. Probably the `RAVEN_DSN` value should be updated to something else...
```
# Sentry/Raven error reporting (server side)
# Enable Raven if you want to help improve funkwhale by
# automatically sending error reports our Sentry instance.
# This will help us detect and correct bugs
RAVEN_ENABLED=false
RAVEN_DSN=https://44332e9fdd3d42879c7d35bf8562c6a4:0062dc16a22b41679cd5765e5342f716@sentry.eliotberriot.com/5
```

**Comment by Jibec** [comment]
hello Josue, what would you expect?

**Comment by Josue-T** [comment]
The question is: it normal that we have this static value for all funkwall instance ?
```
44332e9fdd3d42879c7d35bf8562c6a4:0062dc16a22b41679cd5765e5342f716
```

**Comment by Jibec** [comment]
I think it doesn't really matter as raven is disabled: `RAVEN_ENABLED=false`

**Comment by Josue-T** [comment]
Oh is didn't see that.
