### ISSUE TITLE
channels-redis and python

### ISSUE THREAD

**Issue by renaudponcelet** [YunoHost-Apps/funkwhale_ynh#78]
Hi,
The installation failed with this warning : 

> ERROR: Package 'channels-redis' requires a different Python: 3.5.3 not in '>=3.6'

Have you an idea how can I solve this issue ?
Just to be sure, it is not one of my pythons installed on my machine that is used but a virtual environment created during the installation, right ?

**Comment by Jibec** [comment]
solved by #80
