### ISSUE TITLE
PermissionError [Errno 13]

### ISSUE THREAD

**Issue by Vitriia** [YunoHost-Apps/funkwhale_ynh#81]
Hi, i have got this error when trying a CLI import through a symbolic link.

`Error while importing /var/www/funkwhale/import/**** PermissionError [Errno 13] Permission denied '/var/www/funkwhale/media/albm/covers/***'`

The files are imported but without the picture
The error isn't occuring on all files i don't know why (some files are imported with picture).

Not sure if related with #68

**Comment by Jibec** [comment]
You can try `chown -R funkwhale: /var/www/funkwhale`, but yes, this is also related to #15
