### ISSUE TITLE
beat service fails to start 

### ISSUE THREAD

**Issue by mikerjensen** [YunoHost-Apps/funkwhale_ynh#82]
I can't seem to install funkwhale, even with the testing branch...seems still to be something to do with beat service not starting?

DEBUG      yunohost.app _get_app_status - [12396.1] status file not found for 'funkwhale__4'
Warning: [DEBUG]: Traceback (most recent call last):
Warning: [DEBUG]: File "/usr/lib/moulinette/yunohost/app.py", line 1980, in _get_app_status
Warning: [DEBUG]: with open(app_setting_path + '/status.json') as f:
Warning: [DEBUG]: IOError: [Errno 2] No such file or directory: '/etc/yunohost/apps/funkwhale__4/status.json'
Warning: [DEBUG]: DEBUG      yunohost.app app_setting - [12396.1] cannot get app setting 'update_time' for 'funkwhale__4' ('update_time')
Warning: [DEBUG]: DEBUG      moulinette.authenticator.ldap __init__ - initialize authenticator 'as-root' with: uri='ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi', base_dn='dc=yunohost,dc=org', user_rdn='gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth'
Warning: [DEBUG]: DEBUG      moulinette.actionsmap process - action [12396.1] executed in 0.425s
Warning: [DEBUG]: ERROR    yunohost cli - This url is not available or conflicts with the already installed app(s):
----
i ran:
yunohost log display 20190918-221526-app_install-funkwhale --share

**Comment by Jibec** [comment]
I noticed it too and didn't find the source of it, but it looks like to work fine for my server accross the last 20 days, I'll try to fix it with #83

**Comment by Jibec** [comment]
fixed by #86
