### ISSUE TITLE
Upgrade to v0.20

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/funkwhale_ynh#83]
Just an issue for visibility.

Funkwhale v0.20 was released few days ago.

https://blog.funkwhale.audio/~/Announcements/blog-post-week-2019-40-funkwhale-0.20-is-here

**Comment by Jibec** [comment]
I tried tonight, but it looks like one of the dependencies requires Python 3.6 or more: https://pypi.org/project/websockets/8.0/
And as YunoHost uses Stretch, we are stuck with Python 3.5. I won't install a specific Python 3.6 for now.

**Comment by Jibec** [comment]
fixed by #86
