### ISSUE TITLE
Manually messing with nginx conf file should be avoided at all costs ...

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/funkwhale_ynh#84]
I'm sure there's a good reason for what happens here :

https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/_common.sh#L20

but it's really not recommended to proceed that way ... The nginx configuration is going to be marked as manually modified, and will therefore not be updated to Yunohost's standard, and might even trigger bugs later like in https://forum.yunohost.org/t/i-have-screwed-something-up-royally-please-help/9241 :confused:

**Comment by anmol26s** [comment]
:fearful:

**Comment by Jibec** [comment]
OK, it's not perfect, what do you suggest to fix this?

Should you include the domain creation and deletion in YunoHost core?

Or maybe easier, would force regen the nginx when removing the app solve the issue?

I wouldn't call this "messing with",  as the word is quite aggressive, and as the code addition is a requirement by upstream.

**Comment by alexAubin** [comment]
This was not meant to be agressive and this is not the only app doing that kind of things, and as stated I do understand that there's probably a good reason behind what's done here. But consider that this is triggering a bug that **breaks entire instances because it breaks nginx**, which is not fun for the users affected or the people helping them.

The fix is certainly not to force a regen conf, as that would possibly override legit manual conf tweaks in other pieces of conf performed by the user.

In the general case, I guess the most robust solution is to add a custom regen conf hook (as done by other apps like mailman for example) to properly tweak the nginx conf according to your need during the regenconf. That's not trivial and quite heavy to implement though. 

But in your case, the need for the small piece of config has been reported back like 6~8 months ago and is now included by default in YunoHost : https://github.com/YunoHost/yunohost/blob/stretch-stable/data/templates/nginx/server.tpl.conf#L1

So I'd say there's no tweaking needed anymore - just require Yunohost to be at least 3.6 in your manifest and you're good to go ?

**Comment by Jibec** [comment]
should be fixed by: https://github.com/YunoHost-Apps/funkwhale_ynh/pull/86

**Comment by alexAubin** [comment]
Cheers !

Ideally, just be sure to require yunohost >= 3.6 in the manifest :+1:

**Comment by Jibec** [comment]
Oops, thank you :p
