### ISSUE TITLE
Chrome net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/funkwhale_ynh#87]
Hi,
I was using v0.19.0 for a long time, yesterday (before you merged v0.20.1) I updated to v0.19.1 and it broke Funkwhale for Chrome based browsers (basically all except Firefox).
Page was blank. Nothing showed in the network debug and the console was showing `net::ERR_HTTP2_PROTOCOL_ERROR` 
Here is a screenshot :
![Capture d’écran du 2019-11-03 12-45-07](https://user-images.githubusercontent.com/17988185/68084621-65241d00-fe38-11e9-8825-270fb6ecdc3b.png)

I used the cli `regen-conf`  so my nginx settings are clean. I upgraded to v0.20.1 and issue was still there.

I googled it for some time without success. It seems to be related to chrome being more restrictive on HTTP2.
I could reproduced it, with Chromium 78.0.3904.70 (Build officiel), or Brave or latest Opera.
I've used this guide to debug it (https://www.michalspacek.com/chrome-err_spdy_protocol_error-and-an-invalid-http-header) and I found a ` HTTP2_SESSION_RECV_GOAWAY` in the event :
![Capture d’écran du 2019-11-03 13-02-29](https://user-images.githubusercontent.com/17988185/68084757-4c1c6b80-fe3a-11e9-9184-c1d42830a807.png)
Though it look suspicious I really don't know if it's related... lol

Finally I fixed it by reverting this change :
https://github.com/YunoHost-Apps/funkwhale_ynh/pull/80/files?file-filters%5B%5D=.conf#diff-2da33fb08900b413f2f199fe4ba4aa0f

Then I learned that `add_header` directive overwrites all previous `add_header` in parent block. So I guess it might not be those directives that break things but previous ones in parent file.
(https://www.peterbe.com/plog/be-very-careful-with-your-add_header-in-nginx)
So I changed all `more_set_headers` to `add_header`. Using `curl -I https://funwhale.domain.tld/front/` I can see all headers are correctly set.

It still feels weird because nobody seems to have this issue. I'm up-to-date on nginx and python without tweak. I'll keep `add_header` even if unsecure, I don't know where to look anymore. ^^

**Comment by Epowerj** [comment]
Yeah, I'm having the same issue. Weird that this hasn't gotten more attention.

**Comment by gnouts** [comment]
Updating to 0.20.1 undo the nginx conf changes (Is this a new yunohost thing ? It used to display a warning and kept your changes..)
Applying the change still fix it.

**Comment by Epowerj** [comment]
I might have figured out. Looks like Yunohost sets its own headers when you set up a new separate domain (not a subdomain). I noticed that `/etc/nginx/conf.d/domain.tld.conf` contained `more_set_headers "Content-Security-Policy-Report-Only : default-src https: data: 'unsafe-inline' 'unsafe-eval'";`.

I commented this out and seems to have fixed the issue. Replacing `more_set_headers` with `add_header` in `/etc/nginx/conf.d/domain.tld/funkwhale.conf` effectively just overwrites the headers set by Yunohost.

I have yet to test if federation works with these changes though, so this may not be the ideal solution.

**Comment by Jibec** [comment]
I tried to investigate also last Sunday, but haven't found anything.
If this is the parameter that causes the issue at least we can try different values. The only thing we can't do is to remove all headers.
Thanks for keep trying again and again, we'll find out somehow...

**Comment by Mereck13579** [comment]
Same problem here, tweaked with the headers and in my case only `more_set_headers Cache-Control "public, must-revalidate, proxy-revalidate";`  had to be rolled back to `add_header` for it to work again.

**Comment by filippodb** [comment]
Today I installed funkwhale and it basically can't work on any chromium-based browser because it can't load the Javascripts because of ERR_HTTP2_PROTOCOL_ERROR

>  We're sorry but Funkwhale doesn't work properly without JavaScript enabled. Please enable it to continue

![18c64ce43e7d40ba](https://user-images.githubusercontent.com/7091176/74473946-ced6ad00-4ea4-11ea-9c85-a319237ac851.png)

**Comment by arthurlutz** [comment]
I this might be the same bug as seen on spip_ynh https://github.com/YunoHost-Apps/spip_ynh/issues/11 

The "fix" / workaround was to comment the following line in nginx conf : 

```
 #more_set_headers X-XSS-Protection "1; mode=block";
```

**Comment by Jibec** [comment]
Thank you very much Arthur!

**Comment by Sporiff** [comment]
This should be fixed by #105. The `more_set_headers` syntax was causing issues with the NGINX config. In my testing this has been resolved by the new release.
