### ISSUE TITLE
Restoring the backup ( 0.19.1) but impossible to play tracks and covers that are not visible

### ISSUE THREAD

**Issue by BienOuBien** [YunoHost-Apps/funkwhale_ynh#91]
After the update to 0.20.1 failed on my raspberry pi 3 (ARM) (l[ogs](https://paste.yunohost.org/ahiqafedav.bash)) , I connected to the funkwhale application but couldn't play my music. When I press play, this error message appears on the player and no album covers appears:

> The track cannot be loaded
> You may have connection problems.

So I tried to restore the Funkwhale backup, the restoration is going well but it doesn't change anything. ([logs](https://paste.yunohost.org/oqaziwalob))
I can't listen to anything and no album cover appears either. And when I press the play button I always get the same error message.

**Comment by Jibec** [comment]
this is a duplication of #89
