### ISSUE TITLE
ERROR: django-versatileimagefield 1.10 during installation

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost-Apps/funkwhale_ynh#92]
Hello, j'ai eu cette erreur durant l'installation de funkwhale sur un sous-domaine:

> ERROR: django-versatileimagefield 1.10 has requirement Pillow<6.0.0,>=2.4.0, but you'll have pillow 6.2.1 which is incompatible.

**Comment by Jibec** [comment]
What is the architecture you are using? Does it works now?

**Comment by ImaCrea** [comment]
What do you mean by "architecture"? Would you like my Yunohost diagnostic? 
In the end the installation suceeded and it's all seems to work well. Just wanted to notice that warning message.

**Comment by Jibec** [comment]
OK, thank you. The architecture could be ARM (raspberry pi and equivalent mini PC) or x86 (classical PC). But if it worked, that's the most important.

Warning messages are unfortunately classic for this app and only upstream will be able to fix it. I'll close this bugs report. Enjoy using kresus :)

**Comment by ImaCrea** [comment]
oki it's on a x86
