### ISSUE TITLE
ERROR: botocore 1.13.28 during installation

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost-Apps/funkwhale_ynh#93]
Hello, j'ai rencontré cette erreur durant l'installation de funkwhale sur un sous-domaine:

> ERROR: botocore 1.13.28 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.

**Comment by Jibec** [comment]
What is the architecture you are using? Does it works now?

**Comment by ImaCrea** [comment]
same answer as my other similar issue pblished

**Comment by ImaCrea** [comment]
x86
