### ISSUE TITLE
Embed not working

### ISSUE THREAD

**Issue by unklebonehead** [YunoHost-Apps/funkwhale_ynh#95]
I'm getting a 404 nginx error on the embed. I see that yunohost puts things in different spots. ie the embed code calls to /front/embed.html but that file is actually in /front/code/public/embed.html

Already check with Eliot and he had me try to change some permissions on /var/www/funkwhale/front/ but that has also been moved and it still didnt work. Any ideas?

**Comment by Jibec** [comment]
I never tried to "embed", would you mind telling me how you do this so I can reproduce the error?

**Comment by unklebonehead** [comment]
When you go to an artist or album page there is a "more" button in the header. Click on the dropdown and then embed. Funkwhale will give you an embed code in a customizable iframe.

**Comment by Jibec** [comment]
Ok, the track/artist also have to be available publicly.

First issue to solve was in nginx: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/650b6f4e5e4bdf457fb695a5be57ae342e56ca0b

you can edid manually this file: `/etc/nginx/conf.d/YOURDOMAIN/funkwhale.conf` and then `sudo systemctl reload nginx`

But now, I have an Unauthorized access error, same for you?

**Comment by unklebonehead** [comment]
I cant reload nginx. Is that what you mean by unauthorized access error?

**Comment by unklebonehead** [comment]
Nevermind. I'm a bonehead! I got it restarted. My problem was when I edited /etc/nginx/conf.d/YOURDOMAIN/funkwhale.conf I just copy pasted straight into nano and forgot to remove the other original line. Ended up with a dupilate on line 22. Removed that, restart nginx and viola!

**Comment by Jibec** [comment]
And do you also hit an unauthorized error when you try to embed or does it work for you?

**Comment by unklebonehead** [comment]
No. It is working for me now. 
It might have been something I had tried before. I remember chmod 755 /var/www/funkwhale/code/front this was how discovered it is installed different in Yunohost.

**Comment by unklebonehead** [comment]
My conversation with Eliot can be found on Funkwhale's Loomio. 
https://governance.funkwhale.audio/d/eSn3tLJc/comment/1094

**Comment by Jibec** [comment]
Ok thanks, I'll fix this soon, thank you for identifying the issue and 
to look for a solution :)

**Comment by Jibec** [comment]
so, the last issue is a Funkwhale setting, which I don't know what to do about: https://governance.funkwhale.audio/d/eSn3tLJc/embed-player-into-html5-page/27

I don't know if I can disable this setting in YunoHost and how safe it is for our users..

**Comment by Sporiff** [comment]
The "API Requires Authentication" setting should not be set manually by the installation in my opinion. API authentication is enabled by default as a security measure, and can easily be disabled in the application by the system admin if embeds/public playback are desired. Recent versions of the application display a warning when embedding if the API requires authentication, so the user is prompted to turn this off.

Since the NGINX template has been updated to include the correct settings to allow embedding, I think this can now be closed.
