### ISSUE TITLE
[buster] support for deployment on buster

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/funkwhale_ynh#98]
* [ ] detect postgresql 11 instead of 9.4/9.6

**Comment by arthurlutz** [comment]
Tested with buster install of yunohost gives : https://paste.yunohost.org/raw/ahikofitum

**Comment by arthurlutz** [comment]
https://github.com/YunoHost-Apps/Experimental_helpers/pull/56

**Comment by Jibec** [comment]
Thank your for testing, Alex did already fix the helper: 
https://github.com/YunoHost/yunohost/commit/1ce8cebaae8142d71d9f8d0fce0112c8b4f62a50
So next build should allow you to continue your testing.

**Comment by arthurlutz** [comment]
Thanks for the heads up! Am confused about which branch to use migration-to-buster or buster-unstable

**Comment by arthurlutz** [comment]
New test with updated code from @alexAubin  : 

https://paste.yunohost.org/raw/ehalacafem 

Good bits : 

```
2020-03-10 13:20:31,837: DEBUG - + ynh_psql_create_db '-u funkwhale' funkwhale
2020-03-10 13:20:31,837: DEBUG - + local 'db=-u funkwhale'
2020-03-10 13:20:31,837: DEBUG - + local user=funkwhale
2020-03-10 13:20:31,837: DEBUG - + local 'sql=CREATE DATABASE -u funkwhale;'
[snip]
2020-03-10 13:21:33,292: WARNING - psql: FATAL:  database "funkwhale" does not exist
```

Change of signature for the bash function ?

**Comment by alexAubin** [comment]
That was due to an issue with getopts which is now fixed : https://github.com/YunoHost/yunohost/pull/886 

Tested the install again on my side, now I get a weird authentication issue between psycopg2 and postgresql during the initial migration : 

```text
130323 DEBUG + sudo --login --user=postgres PGUSER=postgres PGPASSWORD=lqr8rMetutxNLEiYVvgOVCy8 psql funkwhale
130725 DEBUG ALTER ROLE
130726 DEBUG + python api/manage.py migrate
131528 WARNING 2020-03-10 20:38:18,969 funkwhale_api.config INFO     Loaded env file at /var/www/funkwhale/code/config/.env
131529 WARNING 2020-03-10 20:38:18,970 funkwhale_api.config INFO     Running with no plugins
135163 WARNING Traceback (most recent call last):
135164 WARNING   File "/var/www/funkwhale/code/virtualenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
135165 WARNING     self.connect()
135166 WARNING   File "/var/www/funkwhale/code/virtualenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
135167 WARNING     self.connection = self.get_new_connection(conn_params)
135167 WARNING   File "/var/www/funkwhale/code/virtualenv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
135168 WARNING     connection = Database.connect(**conn_params)
135168 WARNING   File "/var/www/funkwhale/code/virtualenv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
135178 WARNING     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
135178 WARNING psycopg2.OperationalError: FATAL:  Peer authentication failed for user "funkwhale"
```

But I tested the credentials myself (taken from the .env file then calling `PGUSER=funkwhale PGPASSWORD=thepassword psql funkwhale` from a shell as funkwhale) and they do work...

**Comment by Jibec** [comment]
so, this is a fresh install on Debian Buster and pg_hba.conf contains the proper config `local all all md5`?

**Comment by Jibec** [comment]
if it works with shell as funkwhale and not out of the shell as funkwhale, I assume it's probably a pg_hba.conf issue

**Comment by alexAubin** [comment]
Sooo dunno what happened but actually the CI seems kinda happy and is able to install the app : https://ci-buster.nohost.me/ci/job/47

Only the multiinstance install failed for some reason.

Maybe there was something funky during my test (maybe related to the fact that it was an instance upgraded from stretch ? gotta check if the helpers to handle the pg_hba.conf stuff well in that case)

**Comment by Jibec** [comment]
thank you alex
